# Generated by Django 2.2.4 on 2019-09-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_anser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anser',
            new_name='Answer',
        ),
    ]
